# Setup
title:               AAIIINTT
tagline:             ''
description:         'IAINTAIT algo-sorted blog about all sorts'
url:                 https://www.aaiiintt.xyz
baseurl:             ''
paginate:            100
permalink:           pretty



# About/contact
author:
  name:              Iain Tait
  url:               https://twitter.com/aaiiintt
  email:             aiin@aaiiintt.xyz

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0

# set timezone
timezone: Europe/London